var searchData=
[
  ['a_20basic_20midi_20controller_20sketch_0',['First Output: Creating a Basic MIDI Controller Sketch',['../d5/d7d/md_pages_Getting-Started.html#first-output',1,'']]],
  ['a_20debug_20menu_20in_20the_20arduino_20ide_1',['Adding a &apos;Debug&apos; menu in the Arduino IDE',['../de/daf/md_pages_Debug.html#adding-a-debug-menu-in-the-arduino-ide',1,'']]],
  ['a_20general_20purpose_20midi_20library_2',['Can I use Control Surface as a general purpose MIDI library?',['../da/dc1/FAQ.html#faq-midi',1,'']]],
  ['a_20midi_20address_20variable_3',['Creating a MIDI address variable',['../d3/df7/midi-tutorial.html#midi_md-creating-a-midi-address-variable',1,'']]],
  ['a_20midi_20interface_4',['a MIDI Interface',['../d5/d7d/md_pages_Getting-Started.html#first-output-midi-interface',1,'2. Instantiate a MIDI Interface'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md2-instantiate-a-midi-interface',1,'2. Instantiate a MIDI Interface']]],
  ['a_20midi_20interface_5',['Instantiating, initializing and updating a MIDI interface',['../d3/df7/midi-tutorial.html#midi_md-instantiate-a-midi-interface',1,'']]],
  ['a_20pipe_6',['Filtering or modifying messages passing through a pipe',['../d3/df7/midi-tutorial.html#midi_md-pipes-filtering',1,'']]],
  ['a_20samd11_7',['Arduino boards with a SAMD11',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-a-samd11',1,'']]],
  ['a_20single_20purpose_20usb_20to_20ttl_20chip_8',['Boards with a single-purpose USB-to-TTL chip',['../d8/d4a/md_pages_MIDI-over-USB.html#boards-with-a-single-purpose-usb-to-ttl-chip',1,'']]],
  ['absoluterotaryencoder_9',['AbsoluteRotaryEncoder',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#absoluterotaryencoder',1,'']]],
  ['accessing_20the_20contents_20of_20the_20message_10',['Accessing the contents of the message',['../d3/df7/midi-tutorial.html#midi_md-accessing-the-contents-of-the-message',1,'']]],
  ['adapter_11',['Adapter',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#blemidi-adapter',1,'BLEMIDI-Adapter'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#usbmidi-adapter',1,'USBMIDI-Adapter']]],
  ['add_20extended_20input_20output_20elements_20optional_12',['Add Extended Input Output elements optional',['../d5/d7d/md_pages_Getting-Started.html#first-output-extio',1,'3. Add Extended Input/Output elements (optional)'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md3-add-extended-inputoutput-elements-optional',1,'3. Add Extended Input/Output elements (optional)']]],
  ['add_20midi_20control_20elements_13',['Add MIDI Control Elements',['../d5/d7d/md_pages_Getting-Started.html#autotoc_md4-add-midi-control-elements',1,'4. Add MIDI Control Elements'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md4-add-midi-control-elements-1',1,'4. Add MIDI Control Elements']]],
  ['add_20support_20for_20different_20kinds_20of_20displays_14',['How can I add support for different kinds of displays?',['../da/dc1/FAQ.html#faq-add-display-support',1,'']]],
  ['adding_20a_20debug_20menu_20in_20the_20arduino_20ide_15',['Adding a &apos;Debug&apos; menu in the Arduino IDE',['../de/daf/md_pages_Debug.html#adding-a-debug-menu-in-the-arduino-ide',1,'']]],
  ['adding_20custom_20bitmaps_20to_20display_16',['Adding custom bitmaps to display',['../d1/de7/md_pages_xbm.html',1,'']]],
  ['address_20controller_20number_20midi_20channel_20etc_20at_20runtime_17',['Can I change the address, controller number, MIDI channel, etc. at runtime?',['../da/dc1/FAQ.html#faq-change-address-runtime',1,'']]],
  ['address_20variable_18',['Creating a MIDI address variable',['../d3/df7/midi-tutorial.html#midi_md-creating-a-midi-address-variable',1,'']]],
  ['addresses_19',['addresses',['../da/dc1/FAQ.html#faq-banks-many-addresses',1,'Many addresses'],['../d3/df7/midi-tutorial.html#midi_md-midi-addresses',1,'MIDI addresses']]],
  ['advanced_20',['1.FilteredAnalog-Advanced',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1filteredanalog-advanced',1,'']]],
  ['all_20callbacks_21',['MIDI-Input-Fine-Grained-All-Callbacks',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-input-fine-grained-all-callbacks',1,'']]],
  ['all_20midi_20messages_22',['Send-All-MIDI-Messages',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#send-all-midi-messages',1,'']]],
  ['an_20atmega16u2_20atmega8u2_23',['Arduino boards with an ATmega16U2 (ATmega8U2)',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-an-atmega16u2-atmega8u2',1,'']]],
  ['analogreadserial_24',['1.AnalogReadSerial',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1analogreadserial',1,'']]],
  ['and_20cc_25',['One-Pot-Both-PB-and-CC',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#one-pot-both-pb-and-cc',1,'']]],
  ['and_20extended_20input_20output_26',['Hardware and Extended Input/Output',['../d4/de9/examples.html#examples-hardware-and-extended-input-output',1,'']]],
  ['and_20extensible_27',['Modular and extensible',['../index.html#modular-and-extensible',1,'']]],
  ['and_20high_20level_20“control_20surface”_20code_28',['Combining low-level MIDI code and high-level “Control Surface” code',['../da/dc1/FAQ.html#fac-midi-combine-control-surface',1,'']]],
  ['and_20midi_20controller_20libraries_29',['What&apos;s the difference between the Control Surface and MIDI Controller libraries?',['../da/dc1/FAQ.html#faq-control-surface-vs-midi-controller',1,'']]],
  ['and_20receiving_20midi_20messages_30',['Sending and receiving MIDI messages',['../d4/de9/examples.html#examples-midi-interfaces-sending-and-receiving-midi-messages',1,'']]],
  ['and_20routing_31',['Interfaces, transports and routing',['../d4/de9/examples.html#examples-midi-interfaces-interfaces-transports-and-routing',1,'']]],
  ['and_20updating_32',['Change log and updating',['../index.html#change-log-and-updating',1,'']]],
  ['and_20updating_20a_20midi_20interface_33',['Instantiating, initializing and updating a MIDI interface',['../d3/df7/midi-tutorial.html#midi_md-instantiate-a-midi-interface',1,'']]],
  ['applemidi_34',['AppleMIDI',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#applemidi',1,'']]],
  ['arduino_35',['Arduino',['../d8/da8/md_pages_Installation.html#arduino',1,'']]],
  ['arduino_20boards_36',['Newer, not yet supported Arduino boards',['../d8/d4a/md_pages_MIDI-over-USB.html#newer-not-yet-supported-arduino-boards',1,'']]],
  ['arduino_20boards_20with_20a_20samd11_37',['Arduino boards with a SAMD11',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-a-samd11',1,'']]],
  ['arduino_20boards_20with_20an_20atmega16u2_20atmega8u2_38',['Arduino boards with an ATmega16U2 (ATmega8U2)',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-an-atmega16u2-atmega8u2',1,'']]],
  ['arduino_20boards_20with_20native_20usb_20support_39',['Arduino boards with native USB support',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-native-usb-support',1,'']]],
  ['arduino_20compatible_20boards_40',['Supported Arduino-compatible boards',['../d3/df7/midi-tutorial.html#midi_md-interfaces-supported-boards',1,'']]],
  ['arduino_20ide_41',['Arduino IDE',['../d8/da8/md_pages_Installation.html#autotoc_md2-install-the-library-in-the-arduino-ide',1,'2. Install the Library in the Arduino IDE'],['../de/daf/md_pages_Debug.html#adding-a-debug-menu-in-the-arduino-ide',1,'Adding a &apos;Debug&apos; menu in the Arduino IDE']]],
  ['arduinoblebackend_42',['ArduinoBLEBackend',['../db/d99/md_pages_MIDI-over-BLE.html#arduinoblebackend',1,'']]],
  ['arraysort_43',['ArraySort',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#arraysort',1,'']]],
  ['as_20a_20general_20purpose_20midi_20library_44',['Can I use Control Surface as a general purpose MIDI library?',['../da/dc1/FAQ.html#faq-midi',1,'']]],
  ['asked_20questions_45',['Frequently Asked Questions',['../da/dc1/FAQ.html',1,'']]],
  ['at_20runtime_46',['Can I change the address, controller number, MIDI channel, etc. at runtime?',['../da/dc1/FAQ.html#faq-change-address-runtime',1,'']]],
  ['atmega16u2_20atmega8u2_47',['Arduino boards with an ATmega16U2 (ATmega8U2)',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-an-atmega16u2-atmega8u2',1,'']]],
  ['atmega8u2_48',['Arduino boards with an ATmega16U2 (ATmega8U2)',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-an-atmega16u2-atmega8u2',1,'']]],
  ['audio_49',['Audio',['../index.html#audio',1,'']]]
];
