var searchData=
[
  ['element_0',['Element',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-input-element',1,'Custom-MIDI-Input-Element'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-output-element',1,'Custom-MIDI-Output-Element']]],
  ['element_20bankable_1',['Custom-MIDI-Output-Element-Bankable',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-output-element-bankable',1,'']]],
  ['element_20callback_2',['Custom-Note-LED-Input-Element-Callback',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-note-led-input-element-callback',1,'']]],
  ['element_20callback_20fastled_3',['Custom-Note-LED-Input-Element-Callback-FastLED',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-note-led-input-element-callback-fastled',1,'']]],
  ['elements_4',['Elements',['../d5/d7d/md_pages_Getting-Started.html#autotoc_md4-add-midi-control-elements',1,'4. Add MIDI Control Elements'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md4-add-midi-control-elements-1',1,'4. Add MIDI Control Elements']]],
  ['elements_5',['elements',['../d4/de9/examples.html#examples-midi-input-elements',1,'MIDI input elements'],['../d4/de9/examples.html#examples-midi-output-elements',1,'MIDI output elements'],['../da/dc1/FAQ.html#faq-save-memory-number-of-individual-elements',1,'Reducing the number of individual MIDI elements']]],
  ['elements_20optional_6',['elements optional',['../d5/d7d/md_pages_Getting-Started.html#first-output-extio',1,'3. Add Extended Input/Output elements (optional)'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md3-add-extended-inputoutput-elements-optional',1,'3. Add Extended Input/Output elements (optional)']]],
  ['enable_20disable_7',['Enable-disable',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#enable-disable',1,'']]],
  ['encoder_20selector_20bank_8',['Encoder-Selector-Bank',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#encoder-selector-bank',1,'']]],
  ['encoders_9',['Encoders',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#pin-change-interrupt-encoders',1,'Pin-Change-Interrupt-Encoders'],['../d4/de9/examples.html#examples-midi-output-elements-rotary-encoders',1,'Rotary Encoders'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#timer-interrupt-encoders',1,'Timer-Interrupt-Encoders']]],
  ['encoders_10',['Can I use multiplexers for reading rotary encoders?',['../da/dc1/FAQ.html#faq-mux-encoder',1,'']]],
  ['encoders_20interrupts_11',['MCP23017-Encoders-Interrupts',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcp23017-encoders-interrupts',1,'']]],
  ['encoders_20no_20interrupts_12',['MCP23017-Encoders-No-Interrupts',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcp23017-encoders-no-interrupts',1,'']]],
  ['engineering_13',['Mackie-Control-Universal-Reverse-Engineering',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mackie-control-universal-reverse-engineering',1,'']]],
  ['esp32_14',['ESP32',['../d4/de9/examples.html#examples-board-specific-examples-esp32',1,'']]],
  ['esp32_20boards_20with_20usb_20support_15',['Espressif ESP32 boards with USB support',['../d8/d4a/md_pages_MIDI-over-USB.html#espressif-esp32-boards-with-usb-support',1,'']]],
  ['esp32bluedroidbackend_16',['ESP32BluedroidBackend',['../db/d99/md_pages_MIDI-over-BLE.html#esp32bluedroidbackend',1,'']]],
  ['esp32nimblebackend_17',['ESP32NimBLEBackend',['../db/d99/md_pages_MIDI-over-BLE.html#esp32nimblebackend',1,'']]],
  ['espressif_20boards_18',['Other Espressif boards',['../d8/d4a/md_pages_MIDI-over-USB.html#other-espressif-boards',1,'']]],
  ['espressif_20esp32_20boards_20with_20usb_20support_19',['Espressif ESP32 boards with USB support',['../d8/d4a/md_pages_MIDI-over-USB.html#espressif-esp32-boards-with-usb-support',1,'']]],
  ['etc_20at_20runtime_20',['Can I change the address, controller number, MIDI channel, etc. at runtime?',['../da/dc1/FAQ.html#faq-change-address-runtime',1,'']]],
  ['example_21',['MIDI-Controller-Finished-Example',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-controller-finished-example',1,'']]],
  ['example_22',['example',['../d3/df7/midi-tutorial.html#midi_md-sending-simple-example',1,'Simple example'],['../d3/df7/midi-tutorial.html#midi_md-receiving-simple-example',1,'Simple example']]],
  ['example_20usage_23',['Example usage',['../index.html#example-usage',1,'']]],
  ['examples_24',['Examples',['../d4/de9/examples.html',1,'']]],
  ['examples_25',['examples',['../d4/de9/examples.html#examples-board-specific-examples',1,'Board-specific examples'],['../da/dc1/FAQ.html#faq-midi-examples',1,'MIDI examples'],['../d3/df7/midi-tutorial.html#midi_md-sending-more-examples',1,'More examples'],['../d3/df7/midi-tutorial.html#midi_md-receiving-more-examples',1,'More examples'],['../d3/df7/midi-tutorial.html#midi_md-routing-more-examples',1,'More examples'],['../d4/de9/examples.html#examples-other-examples',1,'Other examples']]],
  ['explanation_26',['Explanation',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#explanation',1,'']]],
  ['extended_20input_20output_27',['Hardware and Extended Input/Output',['../d4/de9/examples.html#examples-hardware-and-extended-input-output',1,'']]],
  ['extended_20input_20output_28',['Extended input/output',['../index.html#extended-inputoutput',1,'']]],
  ['extended_20input_20output_20elements_20optional_29',['Extended Input Output elements optional',['../d5/d7d/md_pages_Getting-Started.html#first-output-extio',1,'3. Add Extended Input/Output elements (optional)'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md3-add-extended-inputoutput-elements-optional',1,'3. Add Extended Input/Output elements (optional)']]],
  ['extending_20the_20library_30',['Extending the library',['../d4/de9/examples.html#examples-extending-the-library',1,'']]],
  ['extensible_31',['Modular and extensible',['../index.html#modular-and-extensible',1,'']]]
];
