# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pieter/GitHub/Control-Surface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pieter/GitHub/Control-Surface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pieter/GitHub/Control-Surface/CMakeFiles /home/pieter/GitHub/Control-Surface/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pieter/GitHub/Control-Surface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named documentation

# Build rule for target.
documentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 documentation
.PHONY : documentation

# fast build rule for target.
documentation/fast:
	$(MAKE) -f CMakeFiles/documentation.dir/build.make CMakeFiles/documentation.dir/build
.PHONY : documentation/fast

#=============================================================================
# Target rules for targets named Control_Surface

# Build rule for target.
Control_Surface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Control_Surface
.PHONY : Control_Surface

# fast build rule for target.
Control_Surface/fast:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/build
.PHONY : Control_Surface/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named ArduinoMock

# Build rule for target.
ArduinoMock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ArduinoMock
.PHONY : ArduinoMock

# fast build rule for target.
ArduinoMock/fast:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/build
.PHONY : ArduinoMock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest/googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

ArduinoMock/Arduino.o: ArduinoMock/Arduino.cpp.o

.PHONY : ArduinoMock/Arduino.o

# target to build an object file
ArduinoMock/Arduino.cpp.o:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Arduino.cpp.o
.PHONY : ArduinoMock/Arduino.cpp.o

ArduinoMock/Arduino.i: ArduinoMock/Arduino.cpp.i

.PHONY : ArduinoMock/Arduino.i

# target to preprocess a source file
ArduinoMock/Arduino.cpp.i:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Arduino.cpp.i
.PHONY : ArduinoMock/Arduino.cpp.i

ArduinoMock/Arduino.s: ArduinoMock/Arduino.cpp.s

.PHONY : ArduinoMock/Arduino.s

# target to generate assembly for a file
ArduinoMock/Arduino.cpp.s:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Arduino.cpp.s
.PHONY : ArduinoMock/Arduino.cpp.s

ArduinoMock/HardwareSerial0.o: ArduinoMock/HardwareSerial0.cpp.o

.PHONY : ArduinoMock/HardwareSerial0.o

# target to build an object file
ArduinoMock/HardwareSerial0.cpp.o:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/HardwareSerial0.cpp.o
.PHONY : ArduinoMock/HardwareSerial0.cpp.o

ArduinoMock/HardwareSerial0.i: ArduinoMock/HardwareSerial0.cpp.i

.PHONY : ArduinoMock/HardwareSerial0.i

# target to preprocess a source file
ArduinoMock/HardwareSerial0.cpp.i:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/HardwareSerial0.cpp.i
.PHONY : ArduinoMock/HardwareSerial0.cpp.i

ArduinoMock/HardwareSerial0.s: ArduinoMock/HardwareSerial0.cpp.s

.PHONY : ArduinoMock/HardwareSerial0.s

# target to generate assembly for a file
ArduinoMock/HardwareSerial0.cpp.s:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/HardwareSerial0.cpp.s
.PHONY : ArduinoMock/HardwareSerial0.cpp.s

ArduinoMock/Print.o: ArduinoMock/Print.cpp.o

.PHONY : ArduinoMock/Print.o

# target to build an object file
ArduinoMock/Print.cpp.o:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Print.cpp.o
.PHONY : ArduinoMock/Print.cpp.o

ArduinoMock/Print.i: ArduinoMock/Print.cpp.i

.PHONY : ArduinoMock/Print.i

# target to preprocess a source file
ArduinoMock/Print.cpp.i:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Print.cpp.i
.PHONY : ArduinoMock/Print.cpp.i

ArduinoMock/Print.s: ArduinoMock/Print.cpp.s

.PHONY : ArduinoMock/Print.s

# target to generate assembly for a file
ArduinoMock/Print.cpp.s:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/Print.cpp.s
.PHONY : ArduinoMock/Print.cpp.s

ArduinoMock/WMath.o: ArduinoMock/WMath.cpp.o

.PHONY : ArduinoMock/WMath.o

# target to build an object file
ArduinoMock/WMath.cpp.o:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/WMath.cpp.o
.PHONY : ArduinoMock/WMath.cpp.o

ArduinoMock/WMath.i: ArduinoMock/WMath.cpp.i

.PHONY : ArduinoMock/WMath.i

# target to preprocess a source file
ArduinoMock/WMath.cpp.i:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/WMath.cpp.i
.PHONY : ArduinoMock/WMath.cpp.i

ArduinoMock/WMath.s: ArduinoMock/WMath.cpp.s

.PHONY : ArduinoMock/WMath.s

# target to generate assembly for a file
ArduinoMock/WMath.cpp.s:
	$(MAKE) -f CMakeFiles/ArduinoMock.dir/build.make CMakeFiles/ArduinoMock.dir/ArduinoMock/WMath.cpp.s
.PHONY : ArduinoMock/WMath.cpp.s

src/Banks/Bank.o: src/Banks/Bank.cpp.o

.PHONY : src/Banks/Bank.o

# target to build an object file
src/Banks/Bank.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Banks/Bank.cpp.o
.PHONY : src/Banks/Bank.cpp.o

src/Banks/Bank.i: src/Banks/Bank.cpp.i

.PHONY : src/Banks/Bank.i

# target to preprocess a source file
src/Banks/Bank.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Banks/Bank.cpp.i
.PHONY : src/Banks/Bank.cpp.i

src/Banks/Bank.s: src/Banks/Bank.cpp.s

.PHONY : src/Banks/Bank.s

# target to generate assembly for a file
src/Banks/Bank.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Banks/Bank.cpp.s
.PHONY : src/Banks/Bank.cpp.s

src/Control_Surface/Control_Surface_Class.o: src/Control_Surface/Control_Surface_Class.cpp.o

.PHONY : src/Control_Surface/Control_Surface_Class.o

# target to build an object file
src/Control_Surface/Control_Surface_Class.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Control_Surface/Control_Surface_Class.cpp.o
.PHONY : src/Control_Surface/Control_Surface_Class.cpp.o

src/Control_Surface/Control_Surface_Class.i: src/Control_Surface/Control_Surface_Class.cpp.i

.PHONY : src/Control_Surface/Control_Surface_Class.i

# target to preprocess a source file
src/Control_Surface/Control_Surface_Class.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Control_Surface/Control_Surface_Class.cpp.i
.PHONY : src/Control_Surface/Control_Surface_Class.cpp.i

src/Control_Surface/Control_Surface_Class.s: src/Control_Surface/Control_Surface_Class.cpp.s

.PHONY : src/Control_Surface/Control_Surface_Class.s

# target to generate assembly for a file
src/Control_Surface/Control_Surface_Class.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Control_Surface/Control_Surface_Class.cpp.s
.PHONY : src/Control_Surface/Control_Surface_Class.cpp.s

src/Hardware/Button.o: src/Hardware/Button.cpp.o

.PHONY : src/Hardware/Button.o

# target to build an object file
src/Hardware/Button.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/Button.cpp.o
.PHONY : src/Hardware/Button.cpp.o

src/Hardware/Button.i: src/Hardware/Button.cpp.i

.PHONY : src/Hardware/Button.i

# target to preprocess a source file
src/Hardware/Button.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/Button.cpp.i
.PHONY : src/Hardware/Button.cpp.i

src/Hardware/Button.s: src/Hardware/Button.cpp.s

.PHONY : src/Hardware/Button.s

# target to generate assembly for a file
src/Hardware/Button.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/Button.cpp.s
.PHONY : src/Hardware/Button.cpp.s

src/Hardware/ExtendedInputOutput/AnalogMultiplex.o: src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.o

.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.o

# target to build an object file
src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.o
.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.o

src/Hardware/ExtendedInputOutput/AnalogMultiplex.i: src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.i

.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.i

# target to preprocess a source file
src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.i
.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.i

src/Hardware/ExtendedInputOutput/AnalogMultiplex.s: src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.s

.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.s

# target to generate assembly for a file
src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.s
.PHONY : src/Hardware/ExtendedInputOutput/AnalogMultiplex.cpp.s

src/Hardware/ExtendedInputOutput/ExtendedIOElement.o: src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.o

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.o

# target to build an object file
src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.o
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.o

src/Hardware/ExtendedInputOutput/ExtendedIOElement.i: src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.i

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.i

# target to preprocess a source file
src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.i
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.i

src/Hardware/ExtendedInputOutput/ExtendedIOElement.s: src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.s

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.s

# target to generate assembly for a file
src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.s
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedIOElement.cpp.s

src/Hardware/ExtendedInputOutput/ExtendedInputOutput.o: src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.o

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.o

# target to build an object file
src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.o
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.o

src/Hardware/ExtendedInputOutput/ExtendedInputOutput.i: src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.i

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.i

# target to preprocess a source file
src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.i
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.i

src/Hardware/ExtendedInputOutput/ExtendedInputOutput.s: src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.s

.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.s

# target to generate assembly for a file
src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.s
.PHONY : src/Hardware/ExtendedInputOutput/ExtendedInputOutput.cpp.s

src/Hardware/ExtendedInputOutput/ShiftRegisterOut.o: src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.o

.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.o

# target to build an object file
src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.o
.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.o

src/Hardware/ExtendedInputOutput/ShiftRegisterOut.i: src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.i

.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.i

# target to preprocess a source file
src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.i
.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.i

src/Hardware/ExtendedInputOutput/ShiftRegisterOut.s: src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.s

.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.s

# target to generate assembly for a file
src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.s
.PHONY : src/Hardware/ExtendedInputOutput/ShiftRegisterOut.cpp.s

src/Helpers/Debug.o: src/Helpers/Debug.cpp.o

.PHONY : src/Helpers/Debug.o

# target to build an object file
src/Helpers/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Debug.cpp.o
.PHONY : src/Helpers/Debug.cpp.o

src/Helpers/Debug.i: src/Helpers/Debug.cpp.i

.PHONY : src/Helpers/Debug.i

# target to preprocess a source file
src/Helpers/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Debug.cpp.i
.PHONY : src/Helpers/Debug.cpp.i

src/Helpers/Debug.s: src/Helpers/Debug.cpp.s

.PHONY : src/Helpers/Debug.s

# target to generate assembly for a file
src/Helpers/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Debug.cpp.s
.PHONY : src/Helpers/Debug.cpp.s

src/Helpers/Exit.o: src/Helpers/Exit.cpp.o

.PHONY : src/Helpers/Exit.o

# target to build an object file
src/Helpers/Exit.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Exit.cpp.o
.PHONY : src/Helpers/Exit.cpp.o

src/Helpers/Exit.i: src/Helpers/Exit.cpp.i

.PHONY : src/Helpers/Exit.i

# target to preprocess a source file
src/Helpers/Exit.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Exit.cpp.i
.PHONY : src/Helpers/Exit.cpp.i

src/Helpers/Exit.s: src/Helpers/Exit.cpp.s

.PHONY : src/Helpers/Exit.s

# target to generate assembly for a file
src/Helpers/Exit.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/Exit.cpp.s
.PHONY : src/Helpers/Exit.cpp.s

src/Helpers/PrintStream.o: src/Helpers/PrintStream.cpp.o

.PHONY : src/Helpers/PrintStream.o

# target to build an object file
src/Helpers/PrintStream.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/PrintStream.cpp.o
.PHONY : src/Helpers/PrintStream.cpp.o

src/Helpers/PrintStream.i: src/Helpers/PrintStream.cpp.i

.PHONY : src/Helpers/PrintStream.i

# target to preprocess a source file
src/Helpers/PrintStream.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/PrintStream.cpp.i
.PHONY : src/Helpers/PrintStream.cpp.i

src/Helpers/PrintStream.s: src/Helpers/PrintStream.cpp.s

.PHONY : src/Helpers/PrintStream.s

# target to generate assembly for a file
src/Helpers/PrintStream.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Helpers/PrintStream.cpp.s
.PHONY : src/Helpers/PrintStream.cpp.s

src/MIDI_Inputs/MIDI_Input_CC.o: src/MIDI_Inputs/MIDI_Input_CC.cpp.o

.PHONY : src/MIDI_Inputs/MIDI_Input_CC.o

# target to build an object file
src/MIDI_Inputs/MIDI_Input_CC.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_CC.cpp.o
.PHONY : src/MIDI_Inputs/MIDI_Input_CC.cpp.o

src/MIDI_Inputs/MIDI_Input_CC.i: src/MIDI_Inputs/MIDI_Input_CC.cpp.i

.PHONY : src/MIDI_Inputs/MIDI_Input_CC.i

# target to preprocess a source file
src/MIDI_Inputs/MIDI_Input_CC.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_CC.cpp.i
.PHONY : src/MIDI_Inputs/MIDI_Input_CC.cpp.i

src/MIDI_Inputs/MIDI_Input_CC.s: src/MIDI_Inputs/MIDI_Input_CC.cpp.s

.PHONY : src/MIDI_Inputs/MIDI_Input_CC.s

# target to generate assembly for a file
src/MIDI_Inputs/MIDI_Input_CC.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_CC.cpp.s
.PHONY : src/MIDI_Inputs/MIDI_Input_CC.cpp.s

src/MIDI_Inputs/MIDI_Input_ChannelPressure.o: src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.o

.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.o

# target to build an object file
src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.o
.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.o

src/MIDI_Inputs/MIDI_Input_ChannelPressure.i: src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.i

.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.i

# target to preprocess a source file
src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.i
.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.i

src/MIDI_Inputs/MIDI_Input_ChannelPressure.s: src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.s

.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.s

# target to generate assembly for a file
src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.s
.PHONY : src/MIDI_Inputs/MIDI_Input_ChannelPressure.cpp.s

src/MIDI_Inputs/MIDI_Input_Note.o: src/MIDI_Inputs/MIDI_Input_Note.cpp.o

.PHONY : src/MIDI_Inputs/MIDI_Input_Note.o

# target to build an object file
src/MIDI_Inputs/MIDI_Input_Note.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_Note.cpp.o
.PHONY : src/MIDI_Inputs/MIDI_Input_Note.cpp.o

src/MIDI_Inputs/MIDI_Input_Note.i: src/MIDI_Inputs/MIDI_Input_Note.cpp.i

.PHONY : src/MIDI_Inputs/MIDI_Input_Note.i

# target to preprocess a source file
src/MIDI_Inputs/MIDI_Input_Note.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_Note.cpp.i
.PHONY : src/MIDI_Inputs/MIDI_Input_Note.cpp.i

src/MIDI_Inputs/MIDI_Input_Note.s: src/MIDI_Inputs/MIDI_Input_Note.cpp.s

.PHONY : src/MIDI_Inputs/MIDI_Input_Note.s

# target to generate assembly for a file
src/MIDI_Inputs/MIDI_Input_Note.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Inputs/MIDI_Input_Note.cpp.s
.PHONY : src/MIDI_Inputs/MIDI_Input_Note.cpp.s

src/MIDI_Interfaces/MIDI_Interface.o: src/MIDI_Interfaces/MIDI_Interface.cpp.o

.PHONY : src/MIDI_Interfaces/MIDI_Interface.o

# target to build an object file
src/MIDI_Interfaces/MIDI_Interface.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Interfaces/MIDI_Interface.cpp.o
.PHONY : src/MIDI_Interfaces/MIDI_Interface.cpp.o

src/MIDI_Interfaces/MIDI_Interface.i: src/MIDI_Interfaces/MIDI_Interface.cpp.i

.PHONY : src/MIDI_Interfaces/MIDI_Interface.i

# target to preprocess a source file
src/MIDI_Interfaces/MIDI_Interface.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Interfaces/MIDI_Interface.cpp.i
.PHONY : src/MIDI_Interfaces/MIDI_Interface.cpp.i

src/MIDI_Interfaces/MIDI_Interface.s: src/MIDI_Interfaces/MIDI_Interface.cpp.s

.PHONY : src/MIDI_Interfaces/MIDI_Interface.s

# target to generate assembly for a file
src/MIDI_Interfaces/MIDI_Interface.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Interfaces/MIDI_Interface.cpp.s
.PHONY : src/MIDI_Interfaces/MIDI_Interface.cpp.s

src/MIDI_Outputs/Abstract/MIDIOutputElement.o: src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.o

.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.o

# target to build an object file
src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.o
.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.o

src/MIDI_Outputs/Abstract/MIDIOutputElement.i: src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.i

.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.i

# target to preprocess a source file
src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.i
.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.i

src/MIDI_Outputs/Abstract/MIDIOutputElement.s: src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.s

.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.s

# target to generate assembly for a file
src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.s
.PHONY : src/MIDI_Outputs/Abstract/MIDIOutputElement.cpp.s

src/MIDI_Parsers/MIDI_Parser.o: src/MIDI_Parsers/MIDI_Parser.cpp.o

.PHONY : src/MIDI_Parsers/MIDI_Parser.o

# target to build an object file
src/MIDI_Parsers/MIDI_Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/MIDI_Parser.cpp.o
.PHONY : src/MIDI_Parsers/MIDI_Parser.cpp.o

src/MIDI_Parsers/MIDI_Parser.i: src/MIDI_Parsers/MIDI_Parser.cpp.i

.PHONY : src/MIDI_Parsers/MIDI_Parser.i

# target to preprocess a source file
src/MIDI_Parsers/MIDI_Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/MIDI_Parser.cpp.i
.PHONY : src/MIDI_Parsers/MIDI_Parser.cpp.i

src/MIDI_Parsers/MIDI_Parser.s: src/MIDI_Parsers/MIDI_Parser.cpp.s

.PHONY : src/MIDI_Parsers/MIDI_Parser.s

# target to generate assembly for a file
src/MIDI_Parsers/MIDI_Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/MIDI_Parser.cpp.s
.PHONY : src/MIDI_Parsers/MIDI_Parser.cpp.s

src/MIDI_Parsers/SerialMIDI_Parser.o: src/MIDI_Parsers/SerialMIDI_Parser.cpp.o

.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.o

# target to build an object file
src/MIDI_Parsers/SerialMIDI_Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/SerialMIDI_Parser.cpp.o
.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.cpp.o

src/MIDI_Parsers/SerialMIDI_Parser.i: src/MIDI_Parsers/SerialMIDI_Parser.cpp.i

.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.i

# target to preprocess a source file
src/MIDI_Parsers/SerialMIDI_Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/SerialMIDI_Parser.cpp.i
.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.cpp.i

src/MIDI_Parsers/SerialMIDI_Parser.s: src/MIDI_Parsers/SerialMIDI_Parser.cpp.s

.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.s

# target to generate assembly for a file
src/MIDI_Parsers/SerialMIDI_Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/SerialMIDI_Parser.cpp.s
.PHONY : src/MIDI_Parsers/SerialMIDI_Parser.cpp.s

src/MIDI_Parsers/USBMIDI_Parser.o: src/MIDI_Parsers/USBMIDI_Parser.cpp.o

.PHONY : src/MIDI_Parsers/USBMIDI_Parser.o

# target to build an object file
src/MIDI_Parsers/USBMIDI_Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/USBMIDI_Parser.cpp.o
.PHONY : src/MIDI_Parsers/USBMIDI_Parser.cpp.o

src/MIDI_Parsers/USBMIDI_Parser.i: src/MIDI_Parsers/USBMIDI_Parser.cpp.i

.PHONY : src/MIDI_Parsers/USBMIDI_Parser.i

# target to preprocess a source file
src/MIDI_Parsers/USBMIDI_Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/USBMIDI_Parser.cpp.i
.PHONY : src/MIDI_Parsers/USBMIDI_Parser.cpp.i

src/MIDI_Parsers/USBMIDI_Parser.s: src/MIDI_Parsers/USBMIDI_Parser.cpp.s

.PHONY : src/MIDI_Parsers/USBMIDI_Parser.s

# target to generate assembly for a file
src/MIDI_Parsers/USBMIDI_Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Parsers/USBMIDI_Parser.cpp.s
.PHONY : src/MIDI_Parsers/USBMIDI_Parser.cpp.s

src/MIDI_Senders/RelativeCCSender.o: src/MIDI_Senders/RelativeCCSender.cpp.o

.PHONY : src/MIDI_Senders/RelativeCCSender.o

# target to build an object file
src/MIDI_Senders/RelativeCCSender.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Senders/RelativeCCSender.cpp.o
.PHONY : src/MIDI_Senders/RelativeCCSender.cpp.o

src/MIDI_Senders/RelativeCCSender.i: src/MIDI_Senders/RelativeCCSender.cpp.i

.PHONY : src/MIDI_Senders/RelativeCCSender.i

# target to preprocess a source file
src/MIDI_Senders/RelativeCCSender.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Senders/RelativeCCSender.cpp.i
.PHONY : src/MIDI_Senders/RelativeCCSender.cpp.i

src/MIDI_Senders/RelativeCCSender.s: src/MIDI_Senders/RelativeCCSender.cpp.s

.PHONY : src/MIDI_Senders/RelativeCCSender.s

# target to generate assembly for a file
src/MIDI_Senders/RelativeCCSender.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/MIDI_Senders/RelativeCCSender.cpp.s
.PHONY : src/MIDI_Senders/RelativeCCSender.cpp.s

src/Selectors/Selector.o: src/Selectors/Selector.cpp.o

.PHONY : src/Selectors/Selector.o

# target to build an object file
src/Selectors/Selector.cpp.o:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Selectors/Selector.cpp.o
.PHONY : src/Selectors/Selector.cpp.o

src/Selectors/Selector.i: src/Selectors/Selector.cpp.i

.PHONY : src/Selectors/Selector.i

# target to preprocess a source file
src/Selectors/Selector.cpp.i:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Selectors/Selector.cpp.i
.PHONY : src/Selectors/Selector.cpp.i

src/Selectors/Selector.s: src/Selectors/Selector.cpp.s

.PHONY : src/Selectors/Selector.s

# target to generate assembly for a file
src/Selectors/Selector.cpp.s:
	$(MAKE) -f CMakeFiles/Control_Surface.dir/build.make CMakeFiles/Control_Surface.dir/src/Selectors/Selector.cpp.s
.PHONY : src/Selectors/Selector.cpp.s

test/Hardware/test-button.o: test/Hardware/test-button.cpp.o

.PHONY : test/Hardware/test-button.o

# target to build an object file
test/Hardware/test-button.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Hardware/test-button.cpp.o
.PHONY : test/Hardware/test-button.cpp.o

test/Hardware/test-button.i: test/Hardware/test-button.cpp.i

.PHONY : test/Hardware/test-button.i

# target to preprocess a source file
test/Hardware/test-button.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Hardware/test-button.cpp.i
.PHONY : test/Hardware/test-button.cpp.i

test/Hardware/test-button.s: test/Hardware/test-button.cpp.s

.PHONY : test/Hardware/test-button.s

# target to generate assembly for a file
test/Hardware/test-button.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Hardware/test-button.cpp.s
.PHONY : test/Hardware/test-button.cpp.s

test/Helpers/test-Array.o: test/Helpers/test-Array.cpp.o

.PHONY : test/Helpers/test-Array.o

# target to build an object file
test/Helpers/test-Array.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/test-Array.cpp.o
.PHONY : test/Helpers/test-Array.cpp.o

test/Helpers/test-Array.i: test/Helpers/test-Array.cpp.i

.PHONY : test/Helpers/test-Array.i

# target to preprocess a source file
test/Helpers/test-Array.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/test-Array.cpp.i
.PHONY : test/Helpers/test-Array.cpp.i

test/Helpers/test-Array.s: test/Helpers/test-Array.cpp.s

.PHONY : test/Helpers/test-Array.s

# target to generate assembly for a file
test/Helpers/test-Array.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/test-Array.cpp.s
.PHONY : test/Helpers/test-Array.cpp.s

test/Helpers/tests-bit-array.o: test/Helpers/tests-bit-array.cpp.o

.PHONY : test/Helpers/tests-bit-array.o

# target to build an object file
test/Helpers/tests-bit-array.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-bit-array.cpp.o
.PHONY : test/Helpers/tests-bit-array.cpp.o

test/Helpers/tests-bit-array.i: test/Helpers/tests-bit-array.cpp.i

.PHONY : test/Helpers/tests-bit-array.i

# target to preprocess a source file
test/Helpers/tests-bit-array.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-bit-array.cpp.i
.PHONY : test/Helpers/tests-bit-array.cpp.i

test/Helpers/tests-bit-array.s: test/Helpers/tests-bit-array.cpp.s

.PHONY : test/Helpers/tests-bit-array.s

# target to generate assembly for a file
test/Helpers/tests-bit-array.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-bit-array.cpp.s
.PHONY : test/Helpers/tests-bit-array.cpp.s

test/Helpers/tests-linked-list.o: test/Helpers/tests-linked-list.cpp.o

.PHONY : test/Helpers/tests-linked-list.o

# target to build an object file
test/Helpers/tests-linked-list.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-linked-list.cpp.o
.PHONY : test/Helpers/tests-linked-list.cpp.o

test/Helpers/tests-linked-list.i: test/Helpers/tests-linked-list.cpp.i

.PHONY : test/Helpers/tests-linked-list.i

# target to preprocess a source file
test/Helpers/tests-linked-list.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-linked-list.cpp.i
.PHONY : test/Helpers/tests-linked-list.cpp.i

test/Helpers/tests-linked-list.s: test/Helpers/tests-linked-list.cpp.s

.PHONY : test/Helpers/tests-linked-list.s

# target to generate assembly for a file
test/Helpers/tests-linked-list.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/Helpers/tests-linked-list.cpp.s
.PHONY : test/Helpers/tests-linked-list.cpp.s

test/MIDI_Inputs/tests-MCU_VU.o: test/MIDI_Inputs/tests-MCU_VU.cpp.o

.PHONY : test/MIDI_Inputs/tests-MCU_VU.o

# target to build an object file
test/MIDI_Inputs/tests-MCU_VU.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Inputs/tests-MCU_VU.cpp.o
.PHONY : test/MIDI_Inputs/tests-MCU_VU.cpp.o

test/MIDI_Inputs/tests-MCU_VU.i: test/MIDI_Inputs/tests-MCU_VU.cpp.i

.PHONY : test/MIDI_Inputs/tests-MCU_VU.i

# target to preprocess a source file
test/MIDI_Inputs/tests-MCU_VU.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Inputs/tests-MCU_VU.cpp.i
.PHONY : test/MIDI_Inputs/tests-MCU_VU.cpp.i

test/MIDI_Inputs/tests-MCU_VU.s: test/MIDI_Inputs/tests-MCU_VU.cpp.s

.PHONY : test/MIDI_Inputs/tests-MCU_VU.s

# target to generate assembly for a file
test/MIDI_Inputs/tests-MCU_VU.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Inputs/tests-MCU_VU.cpp.s
.PHONY : test/MIDI_Inputs/tests-MCU_VU.cpp.s

test/MIDI_Outputs/test-CCButton.o: test/MIDI_Outputs/test-CCButton.cpp.o

.PHONY : test/MIDI_Outputs/test-CCButton.o

# target to build an object file
test/MIDI_Outputs/test-CCButton.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCButton.cpp.o
.PHONY : test/MIDI_Outputs/test-CCButton.cpp.o

test/MIDI_Outputs/test-CCButton.i: test/MIDI_Outputs/test-CCButton.cpp.i

.PHONY : test/MIDI_Outputs/test-CCButton.i

# target to preprocess a source file
test/MIDI_Outputs/test-CCButton.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCButton.cpp.i
.PHONY : test/MIDI_Outputs/test-CCButton.cpp.i

test/MIDI_Outputs/test-CCButton.s: test/MIDI_Outputs/test-CCButton.cpp.s

.PHONY : test/MIDI_Outputs/test-CCButton.s

# target to generate assembly for a file
test/MIDI_Outputs/test-CCButton.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCButton.cpp.s
.PHONY : test/MIDI_Outputs/test-CCButton.cpp.s

test/MIDI_Outputs/test-CCRotaryEncoder.o: test/MIDI_Outputs/test-CCRotaryEncoder.cpp.o

.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.o

# target to build an object file
test/MIDI_Outputs/test-CCRotaryEncoder.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCRotaryEncoder.cpp.o
.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.cpp.o

test/MIDI_Outputs/test-CCRotaryEncoder.i: test/MIDI_Outputs/test-CCRotaryEncoder.cpp.i

.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.i

# target to preprocess a source file
test/MIDI_Outputs/test-CCRotaryEncoder.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCRotaryEncoder.cpp.i
.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.cpp.i

test/MIDI_Outputs/test-CCRotaryEncoder.s: test/MIDI_Outputs/test-CCRotaryEncoder.cpp.s

.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.s

# target to generate assembly for a file
test/MIDI_Outputs/test-CCRotaryEncoder.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-CCRotaryEncoder.cpp.s
.PHONY : test/MIDI_Outputs/test-CCRotaryEncoder.cpp.s

test/MIDI_Outputs/test-NoteButton.o: test/MIDI_Outputs/test-NoteButton.cpp.o

.PHONY : test/MIDI_Outputs/test-NoteButton.o

# target to build an object file
test/MIDI_Outputs/test-NoteButton.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButton.cpp.o
.PHONY : test/MIDI_Outputs/test-NoteButton.cpp.o

test/MIDI_Outputs/test-NoteButton.i: test/MIDI_Outputs/test-NoteButton.cpp.i

.PHONY : test/MIDI_Outputs/test-NoteButton.i

# target to preprocess a source file
test/MIDI_Outputs/test-NoteButton.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButton.cpp.i
.PHONY : test/MIDI_Outputs/test-NoteButton.cpp.i

test/MIDI_Outputs/test-NoteButton.s: test/MIDI_Outputs/test-NoteButton.cpp.s

.PHONY : test/MIDI_Outputs/test-NoteButton.s

# target to generate assembly for a file
test/MIDI_Outputs/test-NoteButton.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButton.cpp.s
.PHONY : test/MIDI_Outputs/test-NoteButton.cpp.s

test/MIDI_Outputs/test-NoteButtonLatching.o: test/MIDI_Outputs/test-NoteButtonLatching.cpp.o

.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.o

# target to build an object file
test/MIDI_Outputs/test-NoteButtonLatching.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonLatching.cpp.o
.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.cpp.o

test/MIDI_Outputs/test-NoteButtonLatching.i: test/MIDI_Outputs/test-NoteButtonLatching.cpp.i

.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.i

# target to preprocess a source file
test/MIDI_Outputs/test-NoteButtonLatching.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonLatching.cpp.i
.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.cpp.i

test/MIDI_Outputs/test-NoteButtonLatching.s: test/MIDI_Outputs/test-NoteButtonLatching.cpp.s

.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.s

# target to generate assembly for a file
test/MIDI_Outputs/test-NoteButtonLatching.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonLatching.cpp.s
.PHONY : test/MIDI_Outputs/test-NoteButtonLatching.cpp.s

test/MIDI_Outputs/test-NoteButtonMatrix.o: test/MIDI_Outputs/test-NoteButtonMatrix.cpp.o

.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.o

# target to build an object file
test/MIDI_Outputs/test-NoteButtonMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonMatrix.cpp.o
.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.cpp.o

test/MIDI_Outputs/test-NoteButtonMatrix.i: test/MIDI_Outputs/test-NoteButtonMatrix.cpp.i

.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.i

# target to preprocess a source file
test/MIDI_Outputs/test-NoteButtonMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonMatrix.cpp.i
.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.cpp.i

test/MIDI_Outputs/test-NoteButtonMatrix.s: test/MIDI_Outputs/test-NoteButtonMatrix.cpp.s

.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.s

# target to generate assembly for a file
test/MIDI_Outputs/test-NoteButtonMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Outputs/test-NoteButtonMatrix.cpp.s
.PHONY : test/MIDI_Outputs/test-NoteButtonMatrix.cpp.s

test/MIDI_Parsers/tests.o: test/MIDI_Parsers/tests.cpp.o

.PHONY : test/MIDI_Parsers/tests.o

# target to build an object file
test/MIDI_Parsers/tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Parsers/tests.cpp.o
.PHONY : test/MIDI_Parsers/tests.cpp.o

test/MIDI_Parsers/tests.i: test/MIDI_Parsers/tests.cpp.i

.PHONY : test/MIDI_Parsers/tests.i

# target to preprocess a source file
test/MIDI_Parsers/tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Parsers/tests.cpp.i
.PHONY : test/MIDI_Parsers/tests.cpp.i

test/MIDI_Parsers/tests.s: test/MIDI_Parsers/tests.cpp.s

.PHONY : test/MIDI_Parsers/tests.s

# target to generate assembly for a file
test/MIDI_Parsers/tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/MIDI_Parsers/tests.cpp.s
.PHONY : test/MIDI_Parsers/tests.cpp.s

test/test_example.o: test/test_example.cpp.o

.PHONY : test/test_example.o

# target to build an object file
test/test_example.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_example.cpp.o
.PHONY : test/test_example.cpp.o

test/test_example.i: test/test_example.cpp.i

.PHONY : test/test_example.i

# target to preprocess a source file
test/test_example.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_example.cpp.i
.PHONY : test/test_example.cpp.i

test/test_example.s: test/test_example.cpp.s

.PHONY : test/test_example.s

# target to generate assembly for a file
test/test_example.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_example.cpp.s
.PHONY : test/test_example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... documentation"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... Control_Surface"
	@echo "... tests"
	@echo "... ArduinoMock"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... ArduinoMock/Arduino.o"
	@echo "... ArduinoMock/Arduino.i"
	@echo "... ArduinoMock/Arduino.s"
	@echo "... ArduinoMock/HardwareSerial0.o"
	@echo "... ArduinoMock/HardwareSerial0.i"
	@echo "... ArduinoMock/HardwareSerial0.s"
	@echo "... ArduinoMock/Print.o"
	@echo "... ArduinoMock/Print.i"
	@echo "... ArduinoMock/Print.s"
	@echo "... ArduinoMock/WMath.o"
	@echo "... ArduinoMock/WMath.i"
	@echo "... ArduinoMock/WMath.s"
	@echo "... src/Banks/Bank.o"
	@echo "... src/Banks/Bank.i"
	@echo "... src/Banks/Bank.s"
	@echo "... src/Control_Surface/Control_Surface_Class.o"
	@echo "... src/Control_Surface/Control_Surface_Class.i"
	@echo "... src/Control_Surface/Control_Surface_Class.s"
	@echo "... src/Hardware/Button.o"
	@echo "... src/Hardware/Button.i"
	@echo "... src/Hardware/Button.s"
	@echo "... src/Hardware/ExtendedInputOutput/AnalogMultiplex.o"
	@echo "... src/Hardware/ExtendedInputOutput/AnalogMultiplex.i"
	@echo "... src/Hardware/ExtendedInputOutput/AnalogMultiplex.s"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedIOElement.o"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedIOElement.i"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedIOElement.s"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedInputOutput.o"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedInputOutput.i"
	@echo "... src/Hardware/ExtendedInputOutput/ExtendedInputOutput.s"
	@echo "... src/Hardware/ExtendedInputOutput/ShiftRegisterOut.o"
	@echo "... src/Hardware/ExtendedInputOutput/ShiftRegisterOut.i"
	@echo "... src/Hardware/ExtendedInputOutput/ShiftRegisterOut.s"
	@echo "... src/Helpers/Debug.o"
	@echo "... src/Helpers/Debug.i"
	@echo "... src/Helpers/Debug.s"
	@echo "... src/Helpers/Exit.o"
	@echo "... src/Helpers/Exit.i"
	@echo "... src/Helpers/Exit.s"
	@echo "... src/Helpers/PrintStream.o"
	@echo "... src/Helpers/PrintStream.i"
	@echo "... src/Helpers/PrintStream.s"
	@echo "... src/MIDI_Inputs/MIDI_Input_CC.o"
	@echo "... src/MIDI_Inputs/MIDI_Input_CC.i"
	@echo "... src/MIDI_Inputs/MIDI_Input_CC.s"
	@echo "... src/MIDI_Inputs/MIDI_Input_ChannelPressure.o"
	@echo "... src/MIDI_Inputs/MIDI_Input_ChannelPressure.i"
	@echo "... src/MIDI_Inputs/MIDI_Input_ChannelPressure.s"
	@echo "... src/MIDI_Inputs/MIDI_Input_Note.o"
	@echo "... src/MIDI_Inputs/MIDI_Input_Note.i"
	@echo "... src/MIDI_Inputs/MIDI_Input_Note.s"
	@echo "... src/MIDI_Interfaces/MIDI_Interface.o"
	@echo "... src/MIDI_Interfaces/MIDI_Interface.i"
	@echo "... src/MIDI_Interfaces/MIDI_Interface.s"
	@echo "... src/MIDI_Outputs/Abstract/MIDIOutputElement.o"
	@echo "... src/MIDI_Outputs/Abstract/MIDIOutputElement.i"
	@echo "... src/MIDI_Outputs/Abstract/MIDIOutputElement.s"
	@echo "... src/MIDI_Parsers/MIDI_Parser.o"
	@echo "... src/MIDI_Parsers/MIDI_Parser.i"
	@echo "... src/MIDI_Parsers/MIDI_Parser.s"
	@echo "... src/MIDI_Parsers/SerialMIDI_Parser.o"
	@echo "... src/MIDI_Parsers/SerialMIDI_Parser.i"
	@echo "... src/MIDI_Parsers/SerialMIDI_Parser.s"
	@echo "... src/MIDI_Parsers/USBMIDI_Parser.o"
	@echo "... src/MIDI_Parsers/USBMIDI_Parser.i"
	@echo "... src/MIDI_Parsers/USBMIDI_Parser.s"
	@echo "... src/MIDI_Senders/RelativeCCSender.o"
	@echo "... src/MIDI_Senders/RelativeCCSender.i"
	@echo "... src/MIDI_Senders/RelativeCCSender.s"
	@echo "... src/Selectors/Selector.o"
	@echo "... src/Selectors/Selector.i"
	@echo "... src/Selectors/Selector.s"
	@echo "... test/Hardware/test-button.o"
	@echo "... test/Hardware/test-button.i"
	@echo "... test/Hardware/test-button.s"
	@echo "... test/Helpers/test-Array.o"
	@echo "... test/Helpers/test-Array.i"
	@echo "... test/Helpers/test-Array.s"
	@echo "... test/Helpers/tests-bit-array.o"
	@echo "... test/Helpers/tests-bit-array.i"
	@echo "... test/Helpers/tests-bit-array.s"
	@echo "... test/Helpers/tests-linked-list.o"
	@echo "... test/Helpers/tests-linked-list.i"
	@echo "... test/Helpers/tests-linked-list.s"
	@echo "... test/MIDI_Inputs/tests-MCU_VU.o"
	@echo "... test/MIDI_Inputs/tests-MCU_VU.i"
	@echo "... test/MIDI_Inputs/tests-MCU_VU.s"
	@echo "... test/MIDI_Outputs/test-CCButton.o"
	@echo "... test/MIDI_Outputs/test-CCButton.i"
	@echo "... test/MIDI_Outputs/test-CCButton.s"
	@echo "... test/MIDI_Outputs/test-CCRotaryEncoder.o"
	@echo "... test/MIDI_Outputs/test-CCRotaryEncoder.i"
	@echo "... test/MIDI_Outputs/test-CCRotaryEncoder.s"
	@echo "... test/MIDI_Outputs/test-NoteButton.o"
	@echo "... test/MIDI_Outputs/test-NoteButton.i"
	@echo "... test/MIDI_Outputs/test-NoteButton.s"
	@echo "... test/MIDI_Outputs/test-NoteButtonLatching.o"
	@echo "... test/MIDI_Outputs/test-NoteButtonLatching.i"
	@echo "... test/MIDI_Outputs/test-NoteButtonLatching.s"
	@echo "... test/MIDI_Outputs/test-NoteButtonMatrix.o"
	@echo "... test/MIDI_Outputs/test-NoteButtonMatrix.i"
	@echo "... test/MIDI_Outputs/test-NoteButtonMatrix.s"
	@echo "... test/MIDI_Parsers/tests.o"
	@echo "... test/MIDI_Parsers/tests.i"
	@echo "... test/MIDI_Parsers/tests.s"
	@echo "... test/test_example.o"
	@echo "... test/test_example.i"
	@echo "... test/test_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

