var searchData=
[
  ['teensy_0',['Teensy',['../d4/de9/examples.html#examples-board-specific-examples-teensy',1,'Teensy'],['../d8/d4a/md_pages_MIDI-over-USB.html#teensy',1,'Teensy']]],
  ['terminology_1',['Terminology',['../da/dc1/FAQ.html#faq-terminology',1,'']]],
  ['the_20address_20controller_20number_20midi_20channel_20etc_20at_20runtime_2',['Can I change the address, controller number, MIDI channel, etc. at runtime?',['../da/dc1/FAQ.html#faq-change-address-runtime',1,'']]],
  ['the_20arduino_20ide_3',['the Arduino IDE',['../d8/da8/md_pages_Installation.html#autotoc_md2-install-the-library-in-the-arduino-ide',1,'2. Install the Library in the Arduino IDE'],['../de/daf/md_pages_Debug.html#adding-a-debug-menu-in-the-arduino-ide',1,'Adding a &apos;Debug&apos; menu in the Arduino IDE']]],
  ['the_20contents_20of_20the_20message_4',['Accessing the contents of the message',['../d3/df7/midi-tutorial.html#midi_md-accessing-the-contents-of-the-message',1,'']]],
  ['the_20control_20surface_5',['the Control Surface',['../d5/d7d/md_pages_Getting-Started.html#first-output-init',1,'5. Initialize the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md5-initialize-the-control-surface',1,'5. Initialize the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#first-output-loop',1,'6. Continuously Update the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md6-continuously-update-the-control-surface',1,'6. Continuously Update the Control Surface']]],
  ['the_20control_20surface_20and_20midi_20controller_20libraries_6',['What&apos;s the difference between the Control Surface and MIDI Controller libraries?',['../da/dc1/FAQ.html#faq-control-surface-vs-midi-controller',1,'']]],
  ['the_20control_5fsurface_20singleton_7',['Purpose of the Control_Surface singleton',['../d8/df5/control-surface-purpose.html',1,'']]],
  ['the_20difference_20between_20the_20control_20surface_20and_20midi_20controller_20libraries_8',['What&apos;s the difference between the Control Surface and MIDI Controller libraries?',['../da/dc1/FAQ.html#faq-control-surface-vs-midi-controller',1,'']]],
  ['the_20finished_20sketch_9',['The finished sketch',['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch',1,'The finished sketch'],['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch-1',1,'The finished sketch']]],
  ['the_20library_10',['the library',['../d5/d7d/md_pages_Getting-Started.html#autotoc_md1-include-the-library',1,'1. Include the library'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md1-include-the-library-1',1,'1. Include the library'],['../d4/de9/examples.html#examples-extending-the-library',1,'Extending the library']]],
  ['the_20library_20in_20the_20arduino_20ide_11',['2. Install the Library in the Arduino IDE',['../d8/da8/md_pages_Installation.html#autotoc_md2-install-the-library-in-the-arduino-ide',1,'']]],
  ['the_20message_12',['Accessing the contents of the message',['../d3/df7/midi-tutorial.html#midi_md-accessing-the-contents-of-the-message',1,'']]],
  ['the_20midi_20protocol_13',['The MIDI protocol',['../d3/df7/midi-tutorial.html#the-midi-protocol',1,'']]],
  ['the_20midi_20software_14',['First Input: Getting Feedback from the MIDI Software',['../d5/d7d/md_pages_Getting-Started.html#first-input',1,'']]],
  ['the_20number_20of_20individual_20midi_20elements_15',['Reducing the number of individual MIDI elements',['../da/dc1/FAQ.html#faq-save-memory-number-of-individual-elements',1,'']]],
  ['through_20a_20pipe_16',['Filtering or modifying messages passing through a pipe',['../d3/df7/midi-tutorial.html#midi_md-pipes-filtering',1,'']]],
  ['timer_17',['BlinkWithoutDelay-Timer',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#blinkwithoutdelay-timer',1,'']]],
  ['timer_20interrupt_20encoders_18',['Timer-Interrupt-Encoders',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#timer-interrupt-encoders',1,'']]],
  ['to_20display_19',['Adding custom bitmaps to display',['../d1/de7/md_pages_xbm.html',1,'']]],
  ['to_20ttl_20chip_20',['Boards with a single-purpose USB-to-TTL chip',['../d8/d4a/md_pages_MIDI-over-USB.html#boards-with-a-single-purpose-usb-to-ttl-chip',1,'']]],
  ['toggle_20leds_21',['Toggle-LEDs',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#toggle-leds',1,'']]],
  ['transports_20and_20routing_22',['Interfaces, transports and routing',['../d4/de9/examples.html#examples-midi-interfaces-interfaces-transports-and-routing',1,'']]],
  ['transpose_20octave_20nc_20button_23',['Transpose-Octave-NC-Button',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#transpose-octave-nc-button',1,'']]],
  ['transposer_24',['Transposer',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#note-manyaddresses-transposer',1,'Note-ManyAddresses-Transposer'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#transposer',1,'Transposer']]],
  ['troubleshooting_25',['Troubleshooting',['../d5/d7d/md_pages_Getting-Started.html#getting-started_md-troubleshooting',1,'']]],
  ['ttl_20chip_26',['Boards with a single-purpose USB-to-TTL chip',['../d8/d4a/md_pages_MIDI-over-USB.html#boards-with-a-single-purpose-usb-to-ttl-chip',1,'']]],
  ['tutorial_27',['MIDI Tutorial',['../d3/df7/midi-tutorial.html',1,'']]]
];
