var searchData=
[
  ['octave_20nc_20button_0',['Transpose-Octave-NC-Button',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#transpose-octave-nc-button',1,'']]],
  ['of_20displays_1',['How can I add support for different kinds of displays?',['../da/dc1/FAQ.html#faq-add-display-support',1,'']]],
  ['of_20individual_20midi_20elements_2',['Reducing the number of individual MIDI elements',['../da/dc1/FAQ.html#faq-save-memory-number-of-individual-elements',1,'']]],
  ['of_20ram_3',['How can I save memory when running out of RAM?',['../da/dc1/FAQ.html#faq-save-memory',1,'']]],
  ['of_20the_20control_5fsurface_20singleton_4',['Purpose of the Control_Surface singleton',['../d8/df5/control-surface-purpose.html',1,'']]],
  ['of_20the_20message_5',['Accessing the contents of the message',['../d3/df7/midi-tutorial.html#midi_md-accessing-the-contents-of-the-message',1,'']]],
  ['oled_6',['MIDI-Monitor-OLED',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-monitor-oled',1,'']]],
  ['oled_20ssd1306_7',['MCU-OLED-SSD1306',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcu-oled-ssd1306',1,'']]],
  ['oled_20ssd1306_20x2_8',['MCU-OLED-SSD1306-x2',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcu-oled-ssd1306-x2',1,'']]],
  ['oled_20usb_20dac_9',['2.VU-Meter-OLED-USB-DAC',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md2vu-meter-oled-usb-dac',1,'']]],
  ['one_20pot_20both_20pb_20and_20cc_10',['One-Pot-Both-PB-and-CC',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#one-pot-both-pb-and-cc',1,'']]],
  ['optional_11',['optional',['../d5/d7d/md_pages_Getting-Started.html#first-output-extio',1,'3. Add Extended Input/Output elements (optional)'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md3-add-extended-inputoutput-elements-optional',1,'3. Add Extended Input/Output elements (optional)']]],
  ['or_20modifying_20messages_20passing_20through_20a_20pipe_12',['Filtering or modifying messages passing through a pipe',['../d3/df7/midi-tutorial.html#midi_md-pipes-filtering',1,'']]],
  ['os_20boards_20with_20native_20usb_20support_13',['Mbed OS boards with native USB support',['../d8/d4a/md_pages_MIDI-over-USB.html#mbed-os-boards-with-native-usb-support',1,'']]],
  ['other_14',['Other',['../d4/de9/examples.html#examples-midi-output-elements-other',1,'Other'],['../d4/de9/examples.html#examples-midi-input-elements-other',1,'Other']]],
  ['other_20espressif_20boards_15',['Other Espressif boards',['../d8/d4a/md_pages_MIDI-over-USB.html#other-espressif-boards',1,'']]],
  ['other_20examples_16',['Other examples',['../d4/de9/examples.html#examples-other-examples',1,'']]],
  ['out_20of_20ram_17',['How can I save memory when running out of RAM?',['../da/dc1/FAQ.html#faq-save-memory',1,'']]],
  ['output_18',['Output',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1first-output',1,'1.First-Output'],['../d4/de9/examples.html#examples-hardware-and-extended-input-output',1,'Hardware and Extended Input/Output'],['../index.html#midi-control-output',1,'MIDI Control Output'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-output',1,'MIDI-Output']]],
  ['output_19',['Extended input/output',['../index.html#extended-inputoutput',1,'']]],
  ['output_20element_20',['Custom-MIDI-Output-Element',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-output-element',1,'']]],
  ['output_20element_20bankable_21',['Custom-MIDI-Output-Element-Bankable',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-output-element-bankable',1,'']]],
  ['output_20elements_22',['MIDI output elements',['../d4/de9/examples.html#examples-midi-output-elements',1,'']]],
  ['output_20elements_20optional_23',['Output elements optional',['../d5/d7d/md_pages_Getting-Started.html#first-output-extio',1,'3. Add Extended Input/Output elements (optional)'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md3-add-extended-inputoutput-elements-optional',1,'3. Add Extended Input/Output elements (optional)']]],
  ['output_3a_20creating_20a_20basic_20midi_20controller_20sketch_24',['First Output: Creating a Basic MIDI Controller Sketch',['../d5/d7d/md_pages_Getting-Started.html#first-output',1,'']]],
  ['over_20ble_25',['MIDI over BLE',['../db/d99/md_pages_MIDI-over-BLE.html',1,'']]],
  ['over_20usb_26',['over USB',['../d8/d4a/md_pages_MIDI-over-USB.html#hiduino-midi-over-usb',1,'HIDUINO MIDI over USB'],['../d8/d4a/md_pages_MIDI-over-USB.html',1,'MIDI over USB']]],
  ['overview_27',['Feature overview',['../index.html#feature-overview',1,'']]]
];
