var searchData=
[
  ['s_20the_20difference_20between_20the_20control_20surface_20and_20midi_20controller_20libraries_0',['What&apos;s the difference between the Control Surface and MIDI Controller libraries?',['../da/dc1/FAQ.html#faq-control-surface-vs-midi-controller',1,'']]],
  ['samd11_1',['Arduino boards with a SAMD11',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-a-samd11',1,'']]],
  ['save_20memory_20when_20running_20out_20of_20ram_2',['How can I save memory when running out of RAM?',['../da/dc1/FAQ.html#faq-save-memory',1,'']]],
  ['selector_20bank_3',['Encoder-Selector-Bank',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#encoder-selector-bank',1,'']]],
  ['selector_20callback_4',['Custom-Selector-Callback',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-selector-callback',1,'']]],
  ['selectors_5',['Banks &amp;amp; Selectors',['../d4/de9/examples.html#examples-banks-selectors',1,'']]],
  ['send_20all_20midi_20messages_6',['Send-All-MIDI-Messages',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#send-all-midi-messages',1,'']]],
  ['send_20midi_20notes_7',['Send-MIDI-Notes',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#send-midi-notes',1,'']]],
  ['send_20receive_8',['SysEx-Send-Receive',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#sysex-send-receive',1,'']]],
  ['sender_9',['Custom-MIDI-Sender',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-midi-sender',1,'']]],
  ['sending_20and_20receiving_20midi_20messages_10',['Sending and receiving MIDI messages',['../d4/de9/examples.html#examples-midi-interfaces-sending-and-receiving-midi-messages',1,'']]],
  ['sending_20midi_11',['Sending MIDI',['../da/dc1/FAQ.html#faq-send-midi',1,'']]],
  ['sending_20midi_20messages_12',['Sending MIDI messages',['../d3/df7/midi-tutorial.html#midi_md-sending',1,'']]],
  ['serial_20interface_13',['Serial-Interface',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#serial-interface',1,'']]],
  ['simple_20example_14',['Simple example',['../d3/df7/midi-tutorial.html#midi_md-sending-simple-example',1,'Simple example'],['../d3/df7/midi-tutorial.html#midi_md-receiving-simple-example',1,'Simple example']]],
  ['single_20purpose_20usb_20to_20ttl_20chip_15',['Boards with a single-purpose USB-to-TTL chip',['../d8/d4a/md_pages_MIDI-over-USB.html#boards-with-a-single-purpose-usb-to-ttl-chip',1,'']]],
  ['singleton_16',['Purpose of the Control_Surface singleton',['../d8/df5/control-surface-purpose.html',1,'']]],
  ['sketch_17',['First Output: Creating a Basic MIDI Controller Sketch',['../d5/d7d/md_pages_Getting-Started.html#first-output',1,'']]],
  ['sketch_18',['sketch',['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch',1,'The finished sketch'],['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch-1',1,'The finished sketch']]],
  ['smart_20control_20change_20potentiometer_19',['Bankable-Smart-Control-Change-Potentiometer',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#bankable-smart-control-change-potentiometer',1,'']]],
  ['software_20',['First Input: Getting Feedback from the MIDI Software',['../d5/d7d/md_pages_Getting-Started.html#first-input',1,'']]],
  ['specific_20examples_21',['Board-specific examples',['../d4/de9/examples.html#examples-board-specific-examples',1,'']]],
  ['specific_20messages_22',['Listening for specific messages',['../d3/df7/midi-tutorial.html#midi_md-listening-for-specific-messages',1,'']]],
  ['spi_20blink_23',['1.SPI-Blink',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1spi-blink',1,'']]],
  ['ssd1306_24',['MCU-OLED-SSD1306',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcu-oled-ssd1306',1,'']]],
  ['ssd1306_20x2_25',['MCU-OLED-SSD1306-x2',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#mcu-oled-ssd1306-x2',1,'']]],
  ['started_26',['Getting Started',['../d5/d7d/md_pages_Getting-Started.html',1,'']]],
  ['started_27',['started',['../d4/de9/examples.html#examples-getting-started',1,'Getting started'],['../index.html#getting-started',1,'Getting started']]],
  ['support_28',['support',['../d8/d4a/md_pages_MIDI-over-USB.html#arduino-boards-with-native-usb-support',1,'Arduino boards with native USB support'],['../index.html#bank-support',1,'Bank support'],['../d8/d4a/md_pages_MIDI-over-USB.html#espressif-esp32-boards-with-usb-support',1,'Espressif ESP32 boards with USB support'],['../d8/d4a/md_pages_MIDI-over-USB.html#mbed-os-boards-with-native-usb-support',1,'Mbed OS boards with native USB support']]],
  ['support_20for_20different_20kinds_20of_20displays_29',['How can I add support for different kinds of displays?',['../da/dc1/FAQ.html#faq-add-display-support',1,'']]],
  ['supported_20arduino_20boards_30',['Newer, not yet supported Arduino boards',['../d8/d4a/md_pages_MIDI-over-USB.html#newer-not-yet-supported-arduino-boards',1,'']]],
  ['supported_20arduino_20compatible_20boards_31',['Supported Arduino-compatible boards',['../d3/df7/midi-tutorial.html#midi_md-interfaces-supported-boards',1,'']]],
  ['supported_20boards_32',['Supported boards',['../index.html#supported-boards',1,'']]],
  ['surface”_20code_33',['Combining low-level MIDI code and high-level “Control Surface” code',['../da/dc1/FAQ.html#fac-midi-combine-control-surface',1,'']]],
  ['surface_34',['Surface',['../d5/d7d/md_pages_Getting-Started.html#first-output-init',1,'5. Initialize the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md5-initialize-the-control-surface',1,'5. Initialize the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#first-output-loop',1,'6. Continuously Update the Control Surface'],['../d5/d7d/md_pages_Getting-Started.html#autotoc_md6-continuously-update-the-control-surface',1,'6. Continuously Update the Control Surface'],['../index.html',1,'Control Surface']]],
  ['surface_20and_20midi_20controller_20libraries_35',['What&apos;s the difference between the Control Surface and MIDI Controller libraries?',['../da/dc1/FAQ.html#faq-control-surface-vs-midi-controller',1,'']]],
  ['surface_20as_20a_20general_20purpose_20midi_20library_36',['Can I use Control Surface as a general purpose MIDI library?',['../da/dc1/FAQ.html#faq-midi',1,'']]],
  ['switches_37',['Buttons &amp;amp; Switches',['../d4/de9/examples.html#examples-midi-output-elements-buttons-switches',1,'']]],
  ['sysex_20send_20receive_38',['SysEx-Send-Receive',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#sysex-send-receive',1,'']]]
];
