var searchData=
[
  ['factories_0',['MIDI pipe factories',['../d3/df7/midi-tutorial.html#midi_md-pipe-factories',1,'']]],
  ['faders_1',['Potentiometers &amp;amp; Faders',['../d4/de9/examples.html#examples-midi-output-elements-potentiometers-faders',1,'']]],
  ['faders_2',['Motorized faders',['../index.html#motorized-faders',1,'']]],
  ['fastled_3',['FastLED',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md9note-fastled',1,'9.Note-FastLED'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#custom-note-led-input-element-callback-fastled',1,'Custom-Note-LED-Input-Element-Callback-FastLED']]],
  ['fastled_20colormapper_4',['10.Note-FastLED-ColorMapper',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md10note-fastled-colormapper',1,'']]],
  ['feature_20overview_5',['Feature overview',['../index.html#feature-overview',1,'']]],
  ['feedback_20from_20the_20midi_20software_6',['First Input: Getting Feedback from the MIDI Software',['../d5/d7d/md_pages_Getting-Started.html#first-input',1,'']]],
  ['filter_7',['MIDI_Pipes-Filter',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi_pipes-filter',1,'']]],
  ['filteredanalog_8',['FilteredAnalog',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1filteredanalog',1,'1.FilteredAnalog'],['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#filteredanalog',1,'FilteredAnalog']]],
  ['filteredanalog_20advanced_9',['1.FilteredAnalog-Advanced',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1filteredanalog-advanced',1,'']]],
  ['filteredanalogreadserial_10',['3.FilteredAnalogReadSerial',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md3filteredanalogreadserial',1,'']]],
  ['filtering_20or_20modifying_20messages_20passing_20through_20a_20pipe_11',['Filtering or modifying messages passing through a pipe',['../d3/df7/midi-tutorial.html#midi_md-pipes-filtering',1,'']]],
  ['fine_20grained_12',['MIDI-Input-Fine-Grained',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-input-fine-grained',1,'']]],
  ['fine_20grained_20all_20callbacks_13',['MIDI-Input-Fine-Grained-All-Callbacks',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-input-fine-grained-all-callbacks',1,'']]],
  ['finished_20example_14',['MIDI-Controller-Finished-Example',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#midi-controller-finished-example',1,'']]],
  ['finished_20sketch_15',['finished sketch',['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch',1,'The finished sketch'],['../d5/d7d/md_pages_Getting-Started.html#the-finished-sketch-1',1,'The finished sketch']]],
  ['first_20input_16',['2.First-Input',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md2first-input',1,'']]],
  ['first_20input_3a_20getting_20feedback_20from_20the_20midi_20software_17',['First Input: Getting Feedback from the MIDI Software',['../d5/d7d/md_pages_Getting-Started.html#first-input',1,'']]],
  ['first_20output_18',['1.First-Output',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#autotoc_md1first-output',1,'']]],
  ['first_20output_3a_20creating_20a_20basic_20midi_20controller_20sketch_19',['First Output: Creating a Basic MIDI Controller Sketch',['../d5/d7d/md_pages_Getting-Started.html#first-output',1,'']]],
  ['for_20different_20kinds_20of_20displays_20',['How can I add support for different kinds of displays?',['../da/dc1/FAQ.html#faq-add-display-support',1,'']]],
  ['for_20reading_20rotary_20encoders_21',['Can I use multiplexers for reading rotary encoders?',['../da/dc1/FAQ.html#faq-mux-encoder',1,'']]],
  ['for_20specific_20messages_22',['Listening for specific messages',['../d3/df7/midi-tutorial.html#midi_md-listening-for-specific-messages',1,'']]],
  ['frequency_20buttons_23',['Blink-Frequency-Buttons',['..//home/runner/work/Control-Surface/Control-Surface/examples/examples.dox#blink-frequency-buttons',1,'']]],
  ['frequently_20asked_20questions_24',['Frequently Asked Questions',['../da/dc1/FAQ.html',1,'']]],
  ['from_20the_20midi_20software_25',['First Input: Getting Feedback from the MIDI Software',['../d5/d7d/md_pages_Getting-Started.html#first-input',1,'']]],
  ['functionality_26',['Functionality',['../d3/df7/midi-tutorial.html#midi_md-interfaces-functionality',1,'']]]
];
